{{ include "celastro.statefulset" (dict "root" . "role" "data") }}
{{- if gt (int .Values.coordinators.replicas) 0 }}
---
{{ include "celastro.statefulset" (dict "root" . "role" "coordinator") }}
{{- end }}
